export { default as Home } from './Home'
export { default as AuthRegister } from './AuthRegister'
export {default as AuthLogin} from './AuthLogin'
export {default as UserPageConfirm} from './UserPageConfirm'
export {default as UserPage} from './UserPage'
export {default as MyPost} from './MyPost'
export {default as UserPost} from './UserPost'