export { default as Home } from './Home'
export { default as AuthRegister } from './AuthRegister'
export {default as AuthLogin} from './AuthLogin'
export {default as User} from './UserPageConfirm'
export {default as UserPage} from './UserPage'
export {default as Post} from './Post'
export {default as PostFriendTag} from './PostFriendTag'